# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: firebase

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  firebase-deploy-holder-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12
    - name: Make Environment
      run: |
        make ci
    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane ios deploy_holder_test_ci

  firebase-deploy-verifier-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12
    - name: Make Environment
      run: |
        make ci
    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane ios deploy_verifier_test_ci       

  firebase-deploy-holder-acc:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12
    - name: Make Environment
      run: |
        make ci
    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane ios deploy_holder_acc_ci

  firebase-deploy-verifier-acc:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12
    - name: Make Environment
      run: |
        make ci
    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane ios deploy_verifier_acc_ci

  firebase-deploy-holder-prod:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12
    - name: Make Environment
      run: |
        make ci
    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane ios deploy_holder_prod_ci

  firebase-deploy-verifier-prod:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12
    - name: Make Environment
      run: |
        make ci
    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane ios deploy_verifier_prod_ci